# Assignment 3 - Computational Mathematics
# Task 1: Iterative method for matrix inversion.

In [29]:
import numpy as np

In [30]:
# Step 1: Define the matrix
A = np.array([[5, 2, 1], [2, 6, 3], [1, 3, 7]], dtype='float64')

# Step 2: Define the initial approximation of B
B = np.eye(A.shape[0]) / np.trace(A)

# Set the accuracy
eps = 1e-6


In [31]:
# Step 3: Iterative method to compute the inverse of matrix
while True:
    # Calculate B using iterative method
    B_next = 2 * B - np.dot(B, np.dot(A, B))
    # Check for convergence
    if np.allclose(B, B_next, atol=eps):
        B = B_next
        break
    B = B_next

In [32]:
# Step 4: Print the resulting inverse matrix
print("The resulting inverse matrix B is:")
print(B)

# Step 5: Compare the result with numpy's 
result = np.linalg.inv(A)
print("The numpy inverse function's result is:")
print(result)

# Check the difference:
print("Difference between the implementations:")
print(result - B)

# Step 4: Print the resulting inverse matrix
print("The resulting inverse matrix B is:")
print(B)

# Step 5: Compare the result with numpy's 
result = np.linalg.inv(A)
print("The numpy inverse function's result is:")
print(result)

# Check the difference:
print("Difference between the implementations:")
print(result - B)


The resulting inverse matrix B is:
[[ 2.30769231e-01 -7.69230769e-02 -1.06490300e-11]
 [-7.69230769e-02  2.37762238e-01 -9.09090909e-02]
 [-1.06490319e-11 -9.09090909e-02  1.81818182e-01]]
The numpy inverse function's result is:
[[ 0.23076923 -0.07692308  0.        ]
 [-0.07692308  0.23776224 -0.09090909]
 [ 0.         -0.09090909  0.18181818]]
Difference between the implementations:
[[ 1.29652400e-11 -1.87996563e-11  1.06490300e-11]
 [-1.87996424e-11  2.72594725e-11 -1.54411345e-11]
 [ 1.06490319e-11 -1.54411206e-11  8.74661454e-12]]
The resulting inverse matrix B is:
[[ 2.30769231e-01 -7.69230769e-02 -1.06490300e-11]
 [-7.69230769e-02  2.37762238e-01 -9.09090909e-02]
 [-1.06490319e-11 -9.09090909e-02  1.81818182e-01]]
The numpy inverse function's result is:
[[ 0.23076923 -0.07692308  0.        ]
 [-0.07692308  0.23776224 -0.09090909]
 [ 0.         -0.09090909  0.18181818]]
Difference between the implementations:
[[ 1.29652400e-11 -1.87996563e-11  1.06490300e-11]
 [-1.87996424e-11  2.

# Task 2: LU factorization and solution of a system of linear equations.

In [33]:
from scipy.linalg import lu  # Import LU decomposition from scipy

# Given matrix A and vector b
A = np.array([[10, -1, 2, 0], 
              [-1, 11, -1, 3], 
              [2, -1, 10, -1], 
              [0, 3, -1, 8]])

b = np.array([5, 20, -10, 15])

# LU factorization using SciPy
P, L, U = lu(A)

In [34]:
# Print matrices L and U
print("Matrix P (Permutation matrix):")
print(P)
print("Matrix L (Lower triangular matrix):")
print(L)
print("\nMatrix U (Upper triangular matrix):")
print(U)


Matrix P (Permutation matrix):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Matrix L (Lower triangular matrix):
[[ 1.          0.          0.          0.        ]
 [-0.1         1.          0.          0.        ]
 [ 0.2        -0.0733945   1.          0.        ]
 [ 0.          0.27522936 -0.08173077  1.        ]]

Matrix U (Upper triangular matrix):
[[10.         -1.          2.          0.        ]
 [ 0.         10.9        -0.8         3.        ]
 [ 0.          0.          9.5412844  -0.77981651]
 [ 0.          0.          0.          7.11057692]]


In [35]:
# Solve the system using LU decomposition
# Step 1: Solve L * y = b
y = np.linalg.solve(L, b)

# Step 2: Solve U * x = y
x = np.linalg.solve(U, y)


In [36]:
# Print the solution vector x
print("\nSolution vector x (using LU decomposition):")
print(x)


Solution vector x (using LU decomposition):
[ 0.82758621  1.48275862 -0.89655172  1.20689655]


In [37]:
# Compare the result with numpy's built-in solver
x_np = np.linalg.solve(A, b)
print("\nSolution vector x (using numpy.linalg.solve):")
print(x_np)


Solution vector x (using numpy.linalg.solve):
[ 0.82758621  1.48275862 -0.89655172  1.20689655]


# Task 3: Finding the Largest Eigenvalue and Vector Using Power Method.

In [38]:
# Given matrix A
A = np.array([[2, -1, 0], 
              [-1, 2, -1], 
              [0, -1, 2]])

# Initial vector v0
v0 = np.array([1, 0, 0], dtype=float)

# Parameters for iteration
tolerance = 1e-6  # Accuracy
max_iterations = 100  # Maximum number of iterations

In [39]:
# Power Iteration Method
def power_method(A, v0, tolerance, max_iterations):
    v = v0 / np.linalg.norm(v0)  # Normalize initial vector
    for _ in range(max_iterations):
        v_next = np.dot(A, v)  # Matrix-vector multiplication
        v_next = v_next / np.linalg.norm(v_next)  # Normalize vector
        
        # Check for convergence
        if np.linalg.norm(v_next - v) < tolerance:
            break
        v = v_next

    # Approximate eigenvalue
    eigenvalue = np.dot(v.T, np.dot(A, v))  # Rayleigh quotient
    return eigenvalue, v

In [40]:
# Apply the power method
largest_eigenvalue, eigenvector = power_method(A, v0, tolerance, max_iterations)

# Print the largest eigenvalue and corresponding eigenvector
print("Largest Eigenvalue (Power Method):", largest_eigenvalue)
print("Corresponding Eigenvector (Power Method):", eigenvector)

Largest Eigenvalue (Power Method): 3.4142135623662
Corresponding Eigenvector (Power Method): [ 0.50000156 -0.70710678  0.49999844]


In [41]:
# Compare with numpy.linalg.eig
eigenvalues, eigenvectors = np.linalg.eig(A)
largest_eigenvalue_np = max(eigenvalues)
largest_eigenvector_np = eigenvectors[:, np.argmax(eigenvalues)]

print("\nLargest Eigenvalue (numpy.linalg.eig):", largest_eigenvalue_np)
print("Corresponding Eigenvector (numpy.linalg.eig):", largest_eigenvector_np)


Largest Eigenvalue (numpy.linalg.eig): 3.4142135623730914
Corresponding Eigenvector (numpy.linalg.eig): [-0.5         0.70710678 -0.5       ]


# Task 4: Comparison of Givens and Householder methods.

# Givens Rotation Method


In [42]:
def givens_rotation(A):
    m, n = A.shape
    Q = np.eye(m)  # Initialize Q as identity
    R = A.copy()   # Copy of A to avoid modifying it directly

    for j in range(n):  # Column
        for i in range(m - 1, j, -1):  # Row
            # Compute Givens rotation matrix G
            a, b = R[i - 1, j], R[i, j]
            r = np.hypot(a, b)  # Compute the hypotenuse
            c, s = a / r, -b / r
            G = np.eye(m)
            G[i - 1, i - 1] = c
            G[i - 1, i] = -s
            G[i, i - 1] = s
            G[i, i] = c

            # Apply G to R
            R = G @ R
            # Accumulate Q
            Q = Q @ G.T

    return Q, R

# Define matrix A
A = np.array([[4, 1, 2, 0],
              [1, 3, 1, 2],
              [2, 1, 5, 1],
              [0, 2, 1, 4]])

# Givens Rotation
Q_givens, R_givens = givens_rotation(A)

print("Givens' Method:")
print("Q matrix:")
print(Q_givens)
print("\nR matrix:")
print(R_givens)

Givens' Method:
Q matrix:
[[ 0.87287156 -0.21398025 -0.38840075  0.203599  ]
 [ 0.21821789  0.77032889 -0.22505464 -0.55527   ]
 [ 0.43643578  0.04279605  0.88932881 -0.129563  ]
 [ 0.          0.59914469  0.08711792  0.79588699]]

R matrix:
[[4.58257569 1.96396101 4.14613991 0.87287156]
 [0.         3.33809184 1.15549333 3.98003258]
 [0.         0.         3.53190586 0.78769123]
 [0.         0.         0.         1.94344499]]


# Householder Reflection Method

In [43]:
def householder_reflection(A):
    m, n = A.shape
    Q = np.eye(m)  # Initialize Q as identity
    R = A.copy()   # Copy of A to avoid modifying it directly

    for j in range(n):  # Iterate over columns
        # Compute the Householder vector
        x = R[j:, j]
        norm_x = np.linalg.norm(x)
        v = x.copy()
        v[0] += np.sign(x[0]) * norm_x
        v = v / np.linalg.norm(v)

        # Construct the Householder matrix H
        H = np.eye(m)
        H[j:, j:] -= 2 * np.outer(v, v)

        # Apply H to R
        R = H @ R
        # Accumulate Q
        Q = Q @ H

    return Q, R

# Householder Reflection
Q_householder, R_householder = householder_reflection(A)

print("\nHouseholder's Method:")
print("Q matrix:")
print(Q_householder)
print("\nR matrix:")
print(R_householder)



Householder's Method:
Q matrix:
[[-0.85507246  0.21843162  0.4131031  -0.22468765]
 [-0.23188406 -0.76571711  0.22695612  0.55533594]
 [-0.46376812 -0.01987474 -0.87513691  0.13659988]
 [ 0.         -0.60462379 -0.10941728 -0.78896003]]

R matrix:
[[-4.57971014e+00 -2.01449275e+00 -4.26086957e+00 -9.27536232e-01]
 [ 6.82598800e-02 -3.30784204e+00 -1.03285136e+00 -3.96980413e+00]
 [ 1.29094719e-01 -5.08938316e-17 -3.43193948e+00 -8.58893792e-01]
 [-7.02148893e-02 -1.32969857e-16  1.11022302e-16 -1.90856835e+00]]


# Task 5: Finding all eigenvalues using Jacobi's method.

In [44]:
def jacobi_method(A, tol=1e-6, max_iterations=100):
    n = A.shape[0]
    V = np.eye(n)  # Eigenvector matrix
    for iteration in range(max_iterations):
        max_val = 0
        p, q = 0, 0
        for i in range(n):
            for j in range(i + 1, n):
                if abs(A[i, j]) > abs(max_val):
                    max_val = A[i, j]
                    p, q = i, j    
        # Check for convergence
        if abs(max_val) < tol:
            break    
        # Compute the rotation angle
        if A[p, p] == A[q, q]:
            theta = np.pi / 4
        else:
            theta = 0.5 * np.arctan(2 * A[p, q] / (A[p, p] - A[q, q]))    
        # Compute cosine and sine
        c = np.cos(theta)
        s = np.sin(theta)   
        R = np.eye(n)
        R[p, p], R[q, q] = c, c
        R[p, q], R[q, p] = s, -s    
        A = R.T @ A @ R
        V = V @ R  # Update eigenvector matrix
    eigenvalues = np.diag(A)
    return eigenvalues, V

In [45]:
# Define the matrix
A = np.array([[1, 1, 0.5],
              [1, 1, 0.25],
              [0.5, 0.25, 2]])

# Apply Jacobi's method
eigenvalues_jacobi, eigenvectors_jacobi = jacobi_method(A)

# Compare with numpy's built-in function
eigenvalues_numpy = np.linalg.eigvals(A)

# Print the results
print("Jacobi's Method Eigenvalues:")
print(eigenvalues_jacobi)

print("\nNumPy Eigenvalues:")
print(eigenvalues_numpy)

Jacobi's Method Eigenvalues:
[1.41291772 2.53642885 0.05065344]

NumPy Eigenvalues:
[-0.01664728  2.53652586  1.48012142]
